### ISSUE TITLE
Not editable after update (2.3.5)

### ISSUE THREAD

**Issue by teodormoq** [scandipwa/menu-organizer#11]
When you try to edit a menu item you getting an error
![Screenshot 2020-05-22 at 13 17 32](https://user-images.githubusercontent.com/8639654/82662801-cd98e700-9c2e-11ea-963d-c1b2c68a9b9a.png)

**Comment by alfredsgenkins** [comment]
Confirmed! Strange. Seems to be broken on Magento 2.3.5 only? Did someone had this issue on 2.3.3?

**Comment by alfredsgenkins** [comment]
Hmm, I am out of ideas. This is for sure coming from `menu-organizer/src/view/adminhtml/web/item-actions-handler.js`. The method failing is: `_openDialogWindow`. I see no reason for it to fail. As more experienced with previous Magento backend, do you have any ideas?

**Comment by alfredsgenkins** [comment]
I can reproduce it on 2.3.3 so looks like a pretty-old issue? 🤔

**Comment by alfredsgenkins** [comment]
Here is what broke it: https://github.com/magento/magento2/commit/6e1822d1b1243a293075e8eef2adc2d6b30d024d#diff-c9a25ed6e3579638a5c75b5c1e9acfd2

I will release a patch today.

**Comment by alfredsgenkins** [comment]
So I made a fix, it is essentially a patch here:

```php
if (is_string(array_key_first($action['url']['params']))) {
    $params = array_merge($action['url']['params'], $params);
} else {
    $params[] = $action['url']['params'];
}
```

If we want to be perfectly cool, I would reference this issue in Magento 2 bug report. However, I do not know if it is worth your time, as the class where the issue is coming from is deprecated. Possibly there are better solutions than mine.

If you could open Magento issues with reference here, would be more than happy to track the status.

**Comment by alfredsgenkins** [comment]
https://github.com/scandipwa/menu-organizer/releases/tag/1.1.8 - reopen if it does not help.
